[mypy]
python_version = 3.11
strict = True
disallow_any_explicit = True
disallow_any_generics = True
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_optional = True
check_untyped_defs = True
show_error_codes = True
files = src, tests

[mypy-tests.*]
disallow_untyped_decorators = False

[[mypy.overrides]]
module = ["alembic.*"]
ignore_missing_imports = True