apiVersion: v1
kind: Service
metadata:
  name: kb-worker
  labels:
    app.kubernetes.io/name: knowledge-be
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: knowledge-be
    app.kubernetes.io/component: worker
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP