"""Adaptive text chunker: heading-aware, heuristic and recursive tiers.

The public entry point is :func:`split` / :func:`split_with_diagnostics` /
:func:`split_parent_child`, which select a tier based on the document profile
and the ``strategy`` hint in :class:`SplitterConfig`. The legacy
:func:`split_text` remains for backwards compatibility.
"""

from __future__ import annotations

from src.core.knowledge.documents.chunker.heading_splitter import (
    HeadingBoundary,
    coalesce_tiny_chunks,
    common_heading_prefix,
    find_heading_boundaries,
    split_by_headings,
)
from src.core.knowledge.documents.chunker.heuristic_splitter import (
    Boundary,
    find_heuristic_boundaries,
    split_by_heuristics,
)
from src.core.knowledge.documents.chunker.patterns import (
    ALL_CAPS_HEADING_PATTERN,
    CHINESE_CHAPTER_PATTERN,
    ENGLISH_CHAPTER_PATTERN,
    EXCESSIVE_BLANKS_PATTERN,
    FORM_FEED_PATTERN,
    GERMAN_CHAPTER_PATTERN,
    MARKDOWN_HEADING_PATTERN,
    NUMBERED_SECTION_PATTERN,
    PAGE_FOOTER_PATTERN,
    PRIO_ALL_CAPS_HEADING,
    PRIO_BLANK_BLOCK,
    PRIO_CHAPTER_MARKER,
    PRIO_FORM_FEED,
    PRIO_NUMBERED_HEAD,
    PRIO_PAGE_FOOTER,
    PRIO_VISUAL_SEP,
    VISUAL_SEPARATOR_PATTERN,
    chapter_patterns_for_langs,
    sentence_separators,
)
from src.core.knowledge.documents.chunker.profiler import (
    DocProfile,
    StrategyTier,
    match_heading,
    profile_document,
    select_strategy,
)
from src.core.knowledge.documents.chunker.splitter import (
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_SEPARATORS,
    ChildChunk,
    Chunk,
    ImageRef,
    ParentChildResult,
    Span,
    SplitterConfig,
    SplitUnit,
    build_chunk,
    compute_overlap,
    default_config,
    extract_image_refs,
    find_semantic_overlap_boundary,
    merge_units,
    protected_spans,
    split_by_separators,
    split_text,
    split_text_parent_child,
    unwrap_linked_images,
)
from src.core.knowledge.documents.chunker.strategy import (
    STRATEGY_AUTO,
    STRATEGY_HEADING,
    STRATEGY_HEURISTIC,
    STRATEGY_LEGACY,
    STRATEGY_RECURSIVE,
    Diagnostics,
    TierRejection,
    ensure_defaults,
    merge_breadcrumbs,
    split,
    split_parent_child,
    split_with_diagnostics,
)
from src.core.knowledge.documents.chunker.tokens import (
    LangChinese,
    LangEnglish,
    LangGerman,
    LangMixed,
    approx_token_count,
    approx_token_count_from_rune_len,
    chars_for_token_limit,
    detect_language,
)
from src.core.knowledge.documents.chunker.validator import (
    ValidationResult,
    validate_chunks,
)

__all__ = [
    "ALL_CAPS_HEADING_PATTERN",
    "CHINESE_CHAPTER_PATTERN",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_SEPARATORS",
    "ENGLISH_CHAPTER_PATTERN",
    "EXCESSIVE_BLANKS_PATTERN",
    "FORM_FEED_PATTERN",
    "GERMAN_CHAPTER_PATTERN",
    "MARKDOWN_HEADING_PATTERN",
    "NUMBERED_SECTION_PATTERN",
    "PAGE_FOOTER_PATTERN",
    "PRIO_ALL_CAPS_HEADING",
    "PRIO_BLANK_BLOCK",
    "PRIO_CHAPTER_MARKER",
    "PRIO_FORM_FEED",
    "PRIO_NUMBERED_HEAD",
    "PRIO_PAGE_FOOTER",
    "PRIO_VISUAL_SEP",
    "STRATEGY_AUTO",
    "STRATEGY_HEADING",
    "STRATEGY_HEURISTIC",
    "STRATEGY_LEGACY",
    "STRATEGY_RECURSIVE",
    "VISUAL_SEPARATOR_PATTERN",
    "Boundary",
    "ChildChunk",
    "Chunk",
    "Diagnostics",
    "DocProfile",
    "HeadingBoundary",
    "ImageRef",
    "LangChinese",
    "LangEnglish",
    "LangGerman",
    "LangMixed",
    "ParentChildResult",
    "Span",
    "SplitUnit",
    "SplitterConfig",
    "StrategyTier",
    "TierRejection",
    "ValidationResult",
    "approx_token_count",
    "approx_token_count_from_rune_len",
    "build_chunk",
    "chapter_patterns_for_langs",
    "chars_for_token_limit",
    "coalesce_tiny_chunks",
    "common_heading_prefix",
    "compute_overlap",
    "default_config",
    "detect_language",
    "ensure_defaults",
    "extract_image_refs",
    "find_heading_boundaries",
    "find_heuristic_boundaries",
    "find_semantic_overlap_boundary",
    "match_heading",
    "merge_breadcrumbs",
    "merge_units",
    "profile_document",
    "protected_spans",
    "select_strategy",
    "sentence_separators",
    "split",
    "split_by_headings",
    "split_by_heuristics",
    "split_by_separators",
    "split_parent_child",
    "split_text",
    "split_text_parent_child",
    "split_with_diagnostics",
    "unwrap_linked_images",
    "validate_chunks",
]
