"""In-process domain event bus for the chat layer.

Mirrors the upstream event-bus contract: a typed ``Event`` payload, an
``EventBus`` registry supporting subscribe / unsubscribe / publish in
both synchronous and fire-and-forget asynchronous modes, and a
lazily-initialized process-wide singleton with package-level helpers.

Handlers are ``async`` callables receiving the ``Event``; a handler
signals failure by raising. Dispatch modes:

- synchronous (default) — :meth:`EventBus.emit` runs handlers in
  registration order and propagates the first failure;
- asynchronous (``async_mode=True``) — :meth:`EventBus.emit` schedules
  each handler as an isolated background task and returns immediately;
  a failing handler is logged and never breaks the other handlers;
- :meth:`EventBus.emit_and_wait` always runs handlers concurrently and
  waits for all of them, then propagates the first failure, regardless
  of the configured mode.

The request-scoped context (tenant / user / request ids) is available
to handlers through the standard contextvars accessors; it is not
threaded as an explicit argument.
"""

from __future__ import annotations

import asyncio
import logging
import threading
from collections.abc import Awaitable, Callable
from dataclasses import dataclass, replace
from typing import TypeAlias
from uuid import uuid4

from src.common.json import JsonObject, JsonValue
from src.core.chat.types import EventType

logger = logging.getLogger(__name__)

# JSON-representable event payload (the concrete bound for the upstream
# ``interface{}`` data slot under the project's no-``Any``/``object`` rule).
EventData: TypeAlias = JsonValue


@dataclass(frozen=True)
class Event:
    """A domain event routed through the event bus.

    ``id`` is auto-generated by the bus on publish when not provided;
    ``metadata`` is an optional free-form JSON object carried along for
    downstream correlation.
    """

    type: EventType
    session_id: str | None = None
    data: EventData | None = None
    metadata: JsonObject | None = None
    request_id: str | None = None
    id: str = ""

    def with_id(self) -> Event:
        """Return a copy carrying a generated id, or ``self`` if one exists."""
        if self.id:
            return self
        return replace(self, id=uuid4().hex)


# An async handler invoked with a single event; raise to signal failure.
EventHandler: TypeAlias = Callable[[Event], Awaitable[None]]


class EventBusError(Exception):
    """Raised when one or more event handlers fail."""


class EventBus:
    """Registry dispatching events to registered handlers.

    Registration and dispatch are guarded by a re-entrant lock so the
    handler map stays consistent even when handlers are registered from
    a different event loop. ``emit`` snapshots the handler list before
    dispatching, so handlers registered mid-flight are not called for an
    in-flight event (mirrors the upstream lock-then-iterate semantics).
    """

    def __init__(self, *, async_mode: bool = False) -> None:
        self._handlers: dict[EventType, list[EventHandler]] = {}
        self._lock = threading.RLock()
        self._async_mode = async_mode
        # Strong references to fire-and-forget tasks so they are never
        # garbage-collected mid-flight; dropped once the task completes.
        self._background_tasks: set[asyncio.Task[None]] = set()

    # ── registration ────────────────────────────────────────────────

    def on(self, event_type: EventType, handler: EventHandler) -> None:
        """Register ``handler`` for ``event_type``.

        Appending the same handler twice registers it twice; duplicate
        registrations are not deduplicated (mirrors the upstream bus).
        """
        with self._lock:
            self._handlers.setdefault(event_type, []).append(handler)

    def subscribe(self, event_type: EventType, handler: EventHandler) -> None:
        """Alias of :meth:`on` — register ``handler`` for ``event_type``."""
        self.on(event_type, handler)

    def off(self, event_type: EventType) -> None:
        """Remove every handler registered for ``event_type``."""
        with self._lock:
            self._handlers.pop(event_type, None)

    def unsubscribe(self, event_type: EventType) -> None:
        """Alias of :meth:`off` — remove every handler for ``event_type``."""
        self.off(event_type)

    # ── dispatch ────────────────────────────────────────────────────

    async def emit(self, event: Event) -> None:
        """Publish ``event`` to every handler registered for its type.

        In synchronous mode handlers run in registration order and the
        first failure aborts with :class:`EventBusError`. In
        asynchronous mode each handler runs as an isolated background
        task; failures are logged, not propagated.
        """
        event = event.with_id()
        handlers = self._snapshot(event.type)
        if not handlers:
            return
        if self._async_mode:
            for handler in handlers:
                task = asyncio.create_task(self._guarded(handler, event))
                self._background_tasks.add(task)
                task.add_done_callback(self._on_task_done)
            return
        for handler in handlers:
            try:
                await handler(event)
            except Exception as exc:
                raise EventBusError(f"event handler failed for {event.type}") from exc

    async def publish(self, event: Event) -> None:
        """Alias of :meth:`emit` — publish ``event`` to its handlers."""
        await self.emit(event)

    async def emit_and_wait(self, event: Event) -> None:
        """Publish ``event`` and run every handler concurrently, awaiting all.

        Raises :class:`EventBusError` when at least one handler fails;
        every handler still completes because all coroutines are awaited
        before any failure is propagated.
        """
        event = event.with_id()
        handlers = self._snapshot(event.type)
        if not handlers:
            return
        results = await asyncio.gather(
            *(handler(event) for handler in handlers),
            return_exceptions=True,
        )
        for result in results:
            if isinstance(result, BaseException):
                if isinstance(result, asyncio.CancelledError):
                    raise result
                raise EventBusError(f"event handler failed for {event.type}") from result

    # ── introspection ───────────────────────────────────────────────

    def has_handlers(self, event_type: EventType) -> bool:
        """Return True when at least one handler is registered."""
        with self._lock:
            return bool(self._handlers.get(event_type))

    def get_handler_count(self, event_type: EventType) -> int:
        """Return the number of handlers registered for ``event_type``."""
        with self._lock:
            return len(self._handlers.get(event_type, ()))

    def clear(self) -> None:
        """Drop every registered handler."""
        with self._lock:
            self._handlers.clear()

    # ── internals ───────────────────────────────────────────────────

    def _snapshot(self, event_type: EventType) -> tuple[EventHandler, ...]:
        """Copy the handler list under the lock for a consistent dispatch."""
        with self._lock:
            return tuple(self._handlers.get(event_type, ()))

    async def _guarded(self, handler: EventHandler, event: Event) -> None:
        """Run one fire-and-forget handler, logging (not raising) failures."""
        try:
            await handler(event)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("event handler failed (type=%s)", event.type)

    def _on_task_done(self, done: asyncio.Future[None]) -> None:
        """Drop a completed fire-and-forget task from the strong-reference set."""
        if isinstance(done, asyncio.Task):
            self._background_tasks.discard(done)


# ── process-wide singleton (mirrors the upstream global bus) ───────────

_global_event_bus: EventBus | None = None


def get_global_event_bus() -> EventBus:
    """Return the process-wide event bus, creating it on first use."""
    global _global_event_bus
    if _global_event_bus is None:
        _global_event_bus = EventBus()
    return _global_event_bus


def set_global_event_bus(bus: EventBus) -> None:
    """Replace the process-wide event bus (used by tests)."""
    global _global_event_bus
    _global_event_bus = bus


def on(event_type: EventType, handler: EventHandler) -> None:
    """Register ``handler`` for ``event_type`` on the process-wide bus."""
    get_global_event_bus().on(event_type, handler)


def off(event_type: EventType) -> None:
    """Remove every handler for ``event_type`` on the process-wide bus."""
    get_global_event_bus().off(event_type)


async def emit(event: Event) -> None:
    """Publish ``event`` on the process-wide bus."""
    await get_global_event_bus().emit(event)


async def emit_and_wait(event: Event) -> None:
    """Publish ``event`` on the process-wide bus and await all handlers."""
    await get_global_event_bus().emit_and_wait(event)


def has_handlers(event_type: EventType) -> bool:
    """Return True when the process-wide bus has a handler registered."""
    return get_global_event_bus().has_handlers(event_type)


def get_handler_count(event_type: EventType) -> int:
    """Return the number of handlers on the process-wide bus."""
    return get_global_event_bus().get_handler_count(event_type)


def clear() -> None:
    """Drop every handler from the process-wide bus."""
    get_global_event_bus().clear()


__all__ = [
    "Event",
    "EventBus",
    "EventBusError",
    "EventData",
    "EventHandler",
    "clear",
    "emit",
    "emit_and_wait",
    "get_global_event_bus",
    "get_handler_count",
    "has_handlers",
    "off",
    "on",
    "set_global_event_bus",
]
