"""Chat pipeline: event-driven stage orchestration.

The engine (``EventManager``) runs plugins registered for pipeline event
types over a shared ``PipelineContext`` carrier; ``types`` and ``common``
hold the step contract and shared utilities that downstream stages build
on.
"""

from __future__ import annotations

from src.core.chat.pipeline.common import (
    ChatMessage,
    ChatModel,
    ChatModelService,
    ChatOptions,
    MessageService,
    ParallelTask,
    StoredMessage,
    append_history_messages,
    append_retrieved_image_output_requirement,
    build_attachments_prompt,
    contains_markdown_image,
    extract_image_captions,
    load_and_process_history,
    parallel_map,
    pipeline_error,
    pipeline_info,
    pipeline_warn,
    prepare_chat_model,
    prepare_messages_with_history,
    render_prompt_placeholders,
    run_parallel,
    strip_think_tags,
)
from src.core.chat.pipeline.context import PipelineContext
from src.core.chat.pipeline.engine import (
    ERR_GET_CHAT_MODEL,
    ERR_GET_HISTORY,
    ERR_GET_RERANK_MODEL,
    ERR_MODEL_CALL,
    ERR_RERANK,
    ERR_SEARCH,
    ERR_SEARCH_NOTHING,
    ERR_TEMPLATE_EXECUTE,
    ERR_TEMPLATE_PARSE,
    EventManager,
    Handler,
    Next,
    Plugin,
    PluginError,
)
from src.core.chat.pipeline.types import (
    PIPELINE_MODES,
    ChatResponse,
    Context,
    EventType,
    FallbackStrategy,
    GraphData,
    GraphNode,
    GraphRelation,
    History,
    MessageAttachment,
    MessageImage,
    PipelineBuilder,
    QueryIntent,
    References,
    SearchResult,
    SearchTarget,
    SearchTargetType,
    SummaryConfig,
    TokenUsage,
)

__all__ = [
    "ERR_GET_CHAT_MODEL",
    "ERR_GET_HISTORY",
    "ERR_GET_RERANK_MODEL",
    "ERR_MODEL_CALL",
    "ERR_RERANK",
    "ERR_SEARCH",
    "ERR_SEARCH_NOTHING",
    "ERR_TEMPLATE_EXECUTE",
    "ERR_TEMPLATE_PARSE",
    "PIPELINE_MODES",
    "ChatMessage",
    "ChatModel",
    "ChatModelService",
    "ChatOptions",
    "ChatResponse",
    "Context",
    "EventManager",
    "EventType",
    "FallbackStrategy",
    "GraphData",
    "GraphNode",
    "GraphRelation",
    "Handler",
    "History",
    "MessageAttachment",
    "MessageImage",
    "MessageService",
    "Next",
    "ParallelTask",
    "PipelineBuilder",
    "PipelineContext",
    "Plugin",
    "PluginError",
    "QueryIntent",
    "References",
    "SearchResult",
    "SearchTarget",
    "SearchTargetType",
    "StoredMessage",
    "SummaryConfig",
    "TokenUsage",
    "append_history_messages",
    "append_retrieved_image_output_requirement",
    "build_attachments_prompt",
    "contains_markdown_image",
    "extract_image_captions",
    "load_and_process_history",
    "parallel_map",
    "pipeline_error",
    "pipeline_info",
    "pipeline_warn",
    "prepare_chat_model",
    "prepare_messages_with_history",
    "render_prompt_placeholders",
    "run_parallel",
    "strip_think_tags",
]
