"""Provider registry and routing helpers for the AI layer.

Public surface: ``ProviderName`` constants, ``ALL_PROVIDERS``,
``detect_provider`` (base-URL routing), the model-name predicates, and the
provider metadata lookup helpers. Downstream chat / embedding / rerank
factories consume these to resolve a configured model to a provider.
"""

from __future__ import annotations

from src.ai.provider.detect import detect_provider
from src.ai.provider.predicates import (
    is_deepseek_model,
    is_lkeap_deepseek_r1_model,
    is_lkeap_deepseek_v3_model,
    is_lkeap_thinking_model,
    is_moonshot_fixed_temp_model,
    is_openai_reasoning_or_gpt5_model,
    is_qwen3_model,
    is_qwen_thinking_model,
)
from src.ai.provider.providers import (
    PROVIDERS,
    get_provider,
    get_provider_or_default,
    list_providers,
    list_providers_by_model_type,
)
from src.ai.provider.registry import (
    ALL_PROVIDERS,
    PROVIDER_ALIYUN,
    PROVIDER_ANTHROPIC,
    PROVIDER_AZURE_OPENAI,
    PROVIDER_DEEPSEEK,
    PROVIDER_GEMINI,
    PROVIDER_GENERIC,
    PROVIDER_GPUSTACK,
    PROVIDER_HUNYUAN,
    PROVIDER_JINA,
    PROVIDER_LKEAP,
    PROVIDER_LONGCAT,
    PROVIDER_MIMO,
    PROVIDER_MINIMAX,
    PROVIDER_MODELSCOPE,
    PROVIDER_MOONSHOT,
    PROVIDER_NOVITA,
    PROVIDER_NVIDIA,
    PROVIDER_OPENAI,
    PROVIDER_OPENROUTER,
    PROVIDER_QIANFAN,
    PROVIDER_QINIU,
    PROVIDER_REQUESTY,
    PROVIDER_SILICONFLOW,
    PROVIDER_VOLCENGINE,
    PROVIDER_WEKNORACLOUD,
    PROVIDER_ZHIPU,
    ModelType,
    ProviderConfig,
    ProviderInfo,
    ProviderName,
)

__all__ = [
    "ALL_PROVIDERS",
    "PROVIDERS",
    "PROVIDER_ALIYUN",
    "PROVIDER_ANTHROPIC",
    "PROVIDER_AZURE_OPENAI",
    "PROVIDER_DEEPSEEK",
    "PROVIDER_GEMINI",
    "PROVIDER_GENERIC",
    "PROVIDER_GPUSTACK",
    "PROVIDER_HUNYUAN",
    "PROVIDER_JINA",
    "PROVIDER_LKEAP",
    "PROVIDER_LONGCAT",
    "PROVIDER_MIMO",
    "PROVIDER_MINIMAX",
    "PROVIDER_MODELSCOPE",
    "PROVIDER_MOONSHOT",
    "PROVIDER_NOVITA",
    "PROVIDER_NVIDIA",
    "PROVIDER_OPENAI",
    "PROVIDER_OPENROUTER",
    "PROVIDER_QIANFAN",
    "PROVIDER_QINIU",
    "PROVIDER_REQUESTY",
    "PROVIDER_SILICONFLOW",
    "PROVIDER_VOLCENGINE",
    "PROVIDER_WEKNORACLOUD",
    "PROVIDER_ZHIPU",
    "ModelType",
    "ProviderConfig",
    "ProviderInfo",
    "ProviderName",
    "detect_provider",
    "get_provider",
    "get_provider_or_default",
    "is_deepseek_model",
    "is_lkeap_deepseek_r1_model",
    "is_lkeap_deepseek_v3_model",
    "is_lkeap_thinking_model",
    "is_moonshot_fixed_temp_model",
    "is_openai_reasoning_or_gpt5_model",
    "is_qwen3_model",
    "is_qwen_thinking_model",
    "list_providers",
    "list_providers_by_model_type",
]
